spring.application.name=InstruDB

#for server
server.port=8080
server.address=0.0.0.0

#for JAVA session timeOut
server.servlet.session.timeout=30m

#for myBatis
mybatis.mapper-locations=classpath:/mapper/*/*.xml

#for myBatis VO alias
mybatis.type-aliases-package= com.inst.project.sample.vo, com.inst.project.user.vo, com.inst.project.admin.vo, com.inst.project.aop.vo, com.inst.project.util

#for myBatis camelCase change
mybatis.configuration.map-underscore-to-camel-case=true

#for JSP
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#for JSP refresh
server.servlet.jsp.init-parameters.development=true

#for Postgre SQL
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:postgresql://192.168.10.142:5432/ezaudit?currentSchema=moimdb
spring.datasource.username=ENC(u6L5fCp2/X7DrCawbTEtfrwlUQoCh+YLi2tJj61lxBvRXmbRqPQx7zE0Xg4MENRK)
spring.datasource.password=ENC(C2NdJl+SGrDs/HcIk23gy63fHj59FSohjuCKS1FIVEZMgY+4a/l0KBEfXV5xSJu4)


#for Email Set 1
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ENC(cWkQC3lmCex8USHbSYEZ2W1X5uihemCjW706QSQ+O1YN+aE2aCzJBknDrs5NBHA2cXDUfVThpryb+wMgA5PmSg==)
spring.mail.password=ENC(wFqe/541geo6U/b7qiOSH1OfAF06OeaLRTGa5TG+xrnvLP63mPKstZ+XalcKCPaIoGmqvo61gvBnArpqJzCuWA==)


#for Email Set 2
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
